Repository ravenclaw900/DietPi-Dashboard, pull requests merged in 2021-11, with the labels that each got.

#30 update readme
  README.md
Labels: documentation

#33 ci(build): add rustfmt and clippy lint steps
  .github/workflows/push-build.yml
Labels: enhancement, rust

#35 fix(frontend): Soft code port for web socket
  src/frontend/src/App.svelte
Labels: bug, javascript
