Repository ravenclaw900/DietPi-Dashboard, pull requests merged in 2022-03, with the labels that each got.

#181 ci(dependabot): Approve and merge non-major bumps
  .github/workflows/dependabot-auto-merge.yml
Labels: dependencies

#182 feat(backend): allow to set log level via config file
  config.toml
  src/backend/src/config.rs
  src/backend/src/main.rs
Labels: enhancement, rust

#186 feat(backend): allow using environment variables to set settings
  src/backend/Cargo.lock
  src/backend/Cargo.toml
  src/backend/src/config.rs
  src/backend/src/main.rs
  src/backend/src/shared.rs
  src/backend/src/socket_handlers.rs
Labels: rust
